name: honey-potion

# This rule triggers when the workflow will run
on:
  push:
    branches:
      - 'tracers/hpota'
      - 'pipelines/ci-cd'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
  schedule:
    - cron: '11 12 * * 1,3,6'
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}


      - name: Build OCI image
        run: |
          docker run -d -p 5000:5000 --name registry registry:latest
          docker compose -f ./compose.yml --progress=plain build hpota
          docker push localhost:5000/hpota:latest

      - name: Retrieve artifact from docker image
        run: |
          # docker create hpota -d localhost:5000/hpota:latest
          docker compose -f ./compose.yml create hpota
          mkdir -p "${{ github.workspace }}"/artifacts/tracers/
          docker cp hpota:/foo.txt "${{ github.workspace }}"/artifacts/tracers/foo.txt

      - name: Archive the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: hpota
          path: ${{ github.workspace }}/artifacts/tracers/foo.txt

  ### make:
  ###   # Specify the operating system for the runner job
  ###   runs-on: ubuntu-latest
  ###   env:
  ###     git_hash: $(git rev-parse --short "$GITHUB_SHA")

  ###   # Steps represent a sequence of tasks that will be executed as part of the job
  ###   steps:
  ###     # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
  ###     - name: Access current repository
  ###       uses: actions/checkout@v4
  ###       with:
  ###         ref: ${{ github.ref }}


  ###     - name: Build OCI image
  ###       run: |
  ###         make hpota

  ###     - name: Retrieve artifact from OCI image
  ###       run: |
  ###         # docker create hpota -d localhost:5000/hpota:latest
  ###         docker compose -f ./compose.yml create hpota
  ###         mkdir -p "${{ github.workspace }}"/artifacts/tracers/
  ###         docker cp hpota:/foo.txt "${{ github.workspace }}"/artifacts/tracers/foo.txt

  ###     - name: Archive the build artifact
  ###       uses: actions/upload-artifact@v4
  ###       with:
  ###         name: hpota
  ###         path: ${{ github.workspace }}/artifacts/tracers/foo.txt



