name: hlcr all-in-one
# builds and packages all high-level container runtimes
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '7 17 * * *'

jobs:
  build_libbpf_bootstrap_android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [gvisor, kata, firecracker]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build OCI image (cross-compile)
      run: |
        make ${{ matrix.arch }}

