name: beetor-bwc

# This rule triggers when the workflow will run
on:
  push:
    branches:
      - 'libkjx/beetor'
      - 'pipelines/ci-cd'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
  schedule:
    - cron: '11 12 * * 1,3,6'
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build_beetor:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: build OCI image
        run: |
          make beetor

      # - name: Build OCI image
      #   run: |
      #     docker run -d -p 5000:5000 --name registry registry:latest
      #     docker compose -f ./compose.yml --progress=plain build beetor
      #     docker push localhost:5000/beetor:latest

      - name: Retrieve artifact from docker image
        run: |
          # docker create beeotr -d localhost:5000/beetor:latest
          docker compose -f ./compose.yml create beetor
          mkdir -p "${{ github.workspace }}"/artifacts/libkjx/
          docker cp beetor:/app/foo-beetor.txt "${{ github.workspace }}"/artifacts/libkjx/foo-beetor.txt

      - name: Archive the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: beetor-foo
          path: ${{ github.workspace }}/artifacts/tracers/foo-beetor.txt


  build_bwc:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: build OCI image
        run: |
          make bwc


      - name: Retrieve artifact from docker image
        run: |
          # docker create beeotr -d localhost:5000/beetor:latest
          docker compose -f ./compose.yml create beetor
          mkdir -p "${{ github.workspace }}"/artifacts/libkjx/
          docker cp beetor:/app/foo-beetor.txt "${{ github.workspace }}"/artifacts/libkjx/foo-beetor.txt

      - name: Archive the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: beetor-foo
          path: ${{ github.workspace }}/artifacts/tracers/foo-beetor.txt

