name: microvm-firecracker
#
on:
  push:
    branches:
      - 'microvms/firecracker'
      - 'pipelines/ci-cd'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
  schedule:
    - cron: '11 12 * * 1,3,6'
  # run the workflow manually from Actions tab
  workflow_dispatch:

jobs:
  build_libbpf_bootstrap_android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [gvisor, kata, firecracker]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build OCI image (cross-compile)
      run: |
        make ${{ matrix.arch }}

