name: gvisor
#
on:
  push:
    branches:
      - 'microvms/aio'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
  schedule:
    - cron: '11 12 * * 1,3,6'
  # run the workflow manually from Actions tab
  workflow_dispatch:
  # run the workflow when called from another workflow
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #  fail-fast: false
    #  matrix:
    #    arch: [gvisor, kata, firecracker]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build OCI image (cross-compile)
      run: |
        docker run -d -p 5000:5000 --name registry registry:3.0
        make mvm-gvisor
        docker push localhost:5000/gvisor:latest

    - name: Retrieve artifact from docker image
      run: |
          docker run -it --name gvisor -d localhost:5000/gvisor:latest
          docker cp gvisor:/gvisor-core.tar.gz ${{ github.workspace }}/artifacts/gvisor-core.tar.gz

    # - name: Archive the build artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: gvisor-core.tar.gz
    #     # image size: 8.48MB
    #     # artifact size: 829.6K
    #     path: ${{ github.workspace }}/artifacts/gvisor-core.tar.gz

