name: hlcr-aio
# builds and packages all high-level container runtimes
on:
  push:
    branches:
      - 'hlcr/aio'
      - 'pipelines/ci-cd'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
  schedule:
    - cron: '11 12 * * 1,3,6'
  # run the workflow manually from Actions tab
  workflow_dispatch:
  # run the workflow when called from another workflow
  #workflow_call:
  workflow_run:
    workflows: [docker, podman, crio]

jobs:
  build_libbpf_bootstrap_android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [gvisor, kata, firecracker]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build OCI image (cross-compile)
      run: |
        make ${{ matrix.arch }}

