name: kata
#
on:
  push:
    branches:
      - 'microvms/aio'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
  schedule:
    - cron: '11 12 * * 1,3,6'
  # run the workflow manually from Actions tab
  workflow_dispatch:
  # run the workflow when called from another workflow
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build OCI image (cross-compile)
      run: |
        make mvm-kata

    - name: Build OCI image (cross-compile)
      run: |
        docker run -d -p 5000:5000 --name registry registry:3.0
        make mvm-kata
        docker push localhost:5000/kata:latest

    - name: Retrieve artifact from docker image
      run: |
        docker run -it --name kata -d localhost:5000/kata:latest
        docker cp kata:/kata-core.tar.gz ${{ github.workspace }}/artifacts/kata-core.tar.gz

